<?php

$page_templates                  = get_page_templates();
$page_templates[ __('Default') ] = '_default';

ksort($page_templates);

$current = get_post_meta($post->ID, '_page_template', true);

?>

<?php wp_nonce_field('cpt_left_sidebar_meta_box', 'cpt_left_sidebar_meta_box_nonce'); ?>

<p>
	<?php echo __('For which template is this left-handed sidebar?') ?><br/>
</p>
<table class="form-table">
    <td>
        <label for="_page_template">
            <?php echo __('Template:') ?>
        </label>
    </td>
    <td>
        <select name="_page_template" id="_page_template">
            <?php foreach ($page_templates as $label => $value): ?>
                <option value="<?php echo $value ?>"
                    <?php selected($current == $value) ?>
                    >
                    <?php echo $label ?>
                </option>
            <?php endforeach; ?>
        </select>
    </td>
</table>


